<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYtdlVyh\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYtdlVyh/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerYtdlVyh.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerYtdlVyh\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerYtdlVyh\App_KernelDevDebugContainer([
    'container.build_hash' => 'YtdlVyh',
    'container.build_id' => 'd53ea658',
    'container.build_time' => 1646660601,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYtdlVyh');
