<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerC8wdGSf\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerC8wdGSf/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerC8wdGSf.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerC8wdGSf\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerC8wdGSf\App_KernelDevDebugContainer([
    'container.build_hash' => 'C8wdGSf',
    'container.build_id' => 'e866cb89',
    'container.build_time' => 1645895987,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerC8wdGSf');
